# Generated by Django 5.2.4 on 2026-01-23 17:14

import store.models.store
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store.thumbnail_upload_to),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store.upload_to),
        ),
    ]
