# Generated by Django 5.2.4 on 2025-11-24 15:59

import product.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=product.models.category.upload_to),
        ),
    ]
