# Generated by Django 5.2.4 on 2025-11-24 19:56

import product.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category.upload_to),
        ),
    ]
