# Generated by Django 5.2.4 on 2025-11-26 16:23

import product.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category.thumbnail_upload_to),
        ),
    ]
