# Generated by Django 5.2.4 on 2025-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='apple', unique=True),
            preserve_default=False,
        ),
    ]
