# Generated by Django 5.2.4 on 2025-12-15 17:41

import product.models.brand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.brand.thumbname_upload_to),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.brand.upload_to),
        ),
    ]
