# Generated by Django 5.2.4 on 2026-01-03 16:03

import tokenshield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenshield', '0002_user_email_verified_user_phone_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=tokenshield.models.upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tokenshield.models.thumbnail_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
