# Generated by Django 5.2.4 on 2025-10-03 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('order_not_received', 'Order Not Received'), ('wrong_item', 'Wrong Item Delivered'), ('damaged_item', 'Damaged Item'), ('late_delivery', 'Late Delivery'), ('return_request', 'Return Request'), ('exchange_request', 'Exchange Request'), ('refund_request', 'Refund Request'), ('payment_failed', 'Payment Failed'), ('double_charged', 'Double Charged'), ('payment_pending', 'Payment Pending'), ('invoice_request', 'Invoice Request'), ('billing_address_issue', 'Billing Address Issue'), ('product_not_listed', 'Product Not Listed'), ('product_info_incorrect', 'Incorrect Product Information'), ('out_of_stock_issue', 'Out of Stock'), ('price_issue', 'Pricing Issue'), ('account_access', 'Account Access Issue'), ('account_verification', 'Account Verification Issue'), ('suspicious_activity', 'Suspicious Account Activity'), ('account_banned', 'Account Banned'), ('coupon_invalid', 'Invalid Coupon'), ('wallet_balance_issue', 'Wallet Balance Issue'), ('wallet_withdrawal_issue', 'Wallet Withdrawal Issue'), ('gift_card_issue', 'Gift Card Issue'), ('vendor_registration', 'Vendor Registration'), ('vendor_payment', 'Vendor Payment Issue'), ('vendor_listing', 'Vendor Listing Issue'), ('vendor_rating_review', 'Vendor Rating/Review Issue'), ('website_bug', 'Website Bug'), ('app_bug', 'App Bug'), ('performance_issue', 'Performance Issue'), ('feature_request', 'Feature Request'), ('tracking_issue', 'Tracking Issue'), ('shipping_partner_issue', 'Shipping Partner Issue'), ('customs_clearance', 'Customs Clearance Issue'), ('fraud_report', 'Fraudulent Activity'), ('counterfeit_product', 'Counterfeit Product'), ('terms_violation', 'Terms/Policy Violation'), ('data_privacy', 'Data Privacy Request'), ('general_inquiry', 'General Inquiry'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticketmessage')),
            ],
        ),
    ]
